<?php
$data = array (
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '婴幼儿奶粉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => '5',
    'level' => 0,
    'id' => '16',
    'name' => '婴幼儿奶粉',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '配方奶粉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '28',
    'name' => '配方奶粉',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '早产奶粉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '早产奶粉',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '羊奶粉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '30',
    'name' => '羊奶粉',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '特色奶粉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '特色奶粉',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '孕妇奶粉',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '孕妇奶粉',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '婴幼儿辅食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '婴幼儿辅食',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '泥糊',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '泥糊',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '冲调类',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '冲调类',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '面条类',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '面条类',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '营养食品/肉松',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '营养食品/肉松',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '长牙期食品',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '长牙期食品',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '果汁',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '营养保健品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '营养保健品',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '放尿用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '放尿用品',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '车/床/椅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '车/床/椅',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '日常用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '日常用品',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '喂养用品',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '启智玩具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '启智玩具',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '睡寝/宝宝服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '睡寝/宝宝服饰',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '婴幼儿洗浴/护肤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '婴幼儿洗浴/护肤',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '图书/影像',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '图书/影像',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '妈妈专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '27',
    'name' => '妈妈专区',
  ),
);
?>